### ISSUE TITLE
Feature: Access Aerial Imagery

### ISSUE THREAD

**Issue by hayjohnny2000** [edina/Bens-Kanban-Board#14]
Scenario: User activates aerial imagery
Scenario: User alters aerial imagery opacity

**Comment by hayjohnny2000** [comment]
https://gitlab.edina.ac.uk/digimap4schools/project-documentation/blob/master/aerial-imagery/user-requirements/features/access-aerial-imagery.feature

**Comment by sfairas** [comment]
- [x] Configure Mapproxy for aerial photography (https://redmine.edina.ac.uk/issues/16091)
- [ ]  Configure tilecache for aerial photography (https://redmine.edina.ac.uk/issues/16092)
- [x]  Implement UI for product selection (https://redmine.edina.ac.uk/issues/16093)
- [ ] Implement product opacity change (https://redmine.edina.ac.uk/issues/16094)
