### ISSUE TITLE
Feature: Saved Map Folder Tree Structure

### ISSUE THREAD

**Issue by hayjohnny2000** [edina/Bens-Kanban-Board#24]

**Comment by hayjohnny2000** [comment]
- https://gitlab.edina.ac.uk/digimap4schools/project-documentation/blob/master/map-manager-folders/user-requirements/tests/features/saved-map-folder-tree-structure.feature

**Comment by hayjohnny2000** [comment]
- [ ] Saved Map Folder Tree Structure: https://redmine.edina.ac.uk/issues/16098
  - [ ] Implement database data model for persisting saved maps in folder hierarchy structure: https://redmine.edina.ac.uk/issues/16099
  - [x] Implement mapper UI features for saved maps in folder hierarchy structure:  https://redmine.edina.ac.uk/issues/16100
  - [ ] Implement application tier functionality for saved maps in folder hierarchy structure: https://redmine.edina.ac.uk/issues/16101
