### ISSUE TITLE
Develop iBeacons App for St. Cecelia's

### ISSUE THREAD

**Issue by colingor** [edina/Bens-Kanban-Board#30]
A Swift app should be developed for http://www.stcecilias.ed.ac.uk/ which will use iBeacons to display webviews containing information about nearby items.
- [x] Create Skeleton app: https://github.com/edina/St-Cecilia-s/issues/1
- [x] Add some collection info to Core Data https://github.com/edina/St-Cecilia-s/issues/2
- [x] Allow external http access https://github.com/edina/St-Cecilia-s/issues/3
- [] Integrate Estimote SDK https://github.com/edina/St-Cecilia-s/issues/4
- [x] Remove Item specific model and controllers from app https://github.com/edina/St-Cecilia-s/issues/5
