### ISSUE TITLE
Address outstanding COBWEB issues

### ISSUE THREAD

**Issue by gmh04** [edina/Bens-Kanban-Board#35]

**Comment by benismobile** [comment]
- [x] Configure Mapproxy for aerial photography (https://redmine.edina.ac.uk/issues/16091)
- [ ]  Configure tilecache for aerial photography (https://redmine.edina.ac.uk/issues/16092)

**Comment by rgamez** [comment]
#### Survey Designer
- [x] [options lost after modifying and saving a survey](https://github.com/edina/fieldtrip-cobweb-project/issues/144)

**Comment by rgamez** [comment]
#### COBWEB App
- [x] [Problems recording the location (GPS/location marker](https://github.com/edina/fieldtrip-cobweb-project/issues/141)
- [x] [Logout screen is popping up](https://github.com/edina/fieldtrip-cobweb-project/issues/130)
- [x] [Thumbnail resize on app doesn't take account of Orientation](https://github.com/edina/fieldtrip-cobweb-project/issues/138)
- [x] [It is not possible to move the location pointer](https://github.com/edina/fieldtrip-cobweb-project/issues/141)
