### ISSUE TITLE
MapView Enhancements (Curious Edinburgh)

### ISSUE THREAD

**Issue by ianfieldhouse** [edina/Bens-Kanban-Board#41]
Currently the button used to centre the map view on the user's current location isn't very discoverable. 
- [x] [The zoom to user's location button should be redesigned so as to be more obvious](https://github.com/edina/Curious-Edinburgh/issues/34).

When the routing information is displayed on the map view the view can look a bit cluttered. 
- [x] [Functionality to hide/show the routing information should be created via a button on the map view directly below the centre map on user's location button](https://github.com/edina/Curious-Edinburgh/issues/35).

The map view  annotations were created before any app artwork was available so should be replaced.
- [x] [Update map view annotations to reflect new app tint colour](https://github.com/edina/Curious-Edinburgh/issues/36).

Not a MapView enhancement but somewhat related
- [x] [Update ListView tour number badges to match app tint](https://github.com/edina/Curious-Edinburgh/issues/38)

**Comment by ianfieldhouse** [comment]
Need to create new beta build in TestFlight for testing.
- [x] Upload new beta build to iTunesConnect
- [x] Submit for beta testing
- [ ] Add to TestFlight for external beta testing

**Comment by ianfieldhouse** [comment]
This no longer requires verification of changes as it is superceded by issue #45.
