### ISSUE TITLE
iOS Knowledge transfer

### ISSUE THREAD

**Issue by benismobile** [edina/Bens-Kanban-Board#5]

**Comment by colingor** [comment]
- [x] Upload iOS app to iTunes Connect [https://github.com/edina/crowdsurvey/issues/69]
- [x] Distribute an app with TestFlight
  [https://github.com/edina/crowdsurvey/issues/70]
- [x] Setup initial app information in app store [edina/crowdsurvey/issues/71]
- [x] Add further resources page with useful iOS info [https://github.com/edina/crowdsurvey/issues/72]

**Comment by ianfieldhouse** [comment]
See Crowd Survey wiki.

https://github.com/edina/crowdsurvey/wiki/iOS-Tutorials

**Comment by benismobile** [comment]
- [x] Setup initial app information in app store
- [x] Uploading an app to iTunes Connect
- [x]  Distribute an app with TestFlight
