### ISSUE TITLE
Curious Edinburgh Error Handling

### ISSUE THREAD

**Issue by ianfieldhouse** [edina/Bens-Kanban-Board#50]
There are a number of situations where the app can end up in a state where some or all of the information relating to a tour is missing. Currently these situations occur silently and the user can be left in a situation where they are unsure as to what has happened.

The following situations have been identified and should be handled in a manner that doesn't lead to confusion for the user:
- [ ] [the device is offline: inform the user and load existing data if available](https://github.com/edina/Curious-Edinburgh/issues/41)
- [ ] [the requests to Apple's routing service fail: hide/disable the routing button](https://github.com/edina/Curious-Edinburgh/issues/42)
- [ ] [blog url loaded but no tour POI exist: inform user and reload previous tour if available](https://github.com/edina/Curious-Edinburgh/issues/43)
